CREATE TABLE poll_answer
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_poll_answer PRIMARY KEY (id)
);